version: '3.8'

services:
  client:
    build:
      context: ./Taskflow-client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - api

  api:
    build:
      context: ./Taskflow-server
      dockerfile: Dockerfile
    container_name: taskflow-api
    ports:
      - "5000:5000"