version: '3.8'

services:
  client:
    build: ./Taskflow-client
    ports:
      - "3000:80"
    depends_on:
      - api

  api:
    build: ./Taskflow-server
    container_name: taskflow-api
    ports:
      - "5000:5000"